//
// Created by 48782 on 25.07.2023.
//

#ifndef PATHFINDINGALGORITHMSCOMPARISON_ALGORITHM_H
#define PATHFINDINGALGORITHMSCOMPARISON_ALGORITHM_H


class Algorithm {

};


#endif //PATHFINDINGALGORITHMSCOMPARISON_ALGORITHM_H
